SeakerSop/Controllers/MainPageController.cs
using Microsoft.AspNetCore.Mvc;
using SeakerSop.Models;
using System.Diagnostics;

namespace SeakerSop.Controllers
{
    public class MainPageController : Controller
    {
        private readonly ILogger<MainPageController> _logger;

        public MainPageController(ILogger<MainPageController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View("MainPageView");
        }

        public IActionResult Privacy()
        {
           
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SeakerSop/Controllers/ManProductController.cs
using Microsoft.AspNetCore.Mvc;
using SeakerSop.Models;
using SeakerSop.Repository;
using System.Diagnostics.Metrics;
using System.Drawing;

namespace SeakerSop.Controllers
{
    public class ManProductController : Controller
    {
        private readonly IRepository Repository;
        private readonly DbContextApplication _Context;
        private readonly IQueryable<SneakersProduct> ManSneakersViewData;
        public ManProductController(DbContextApplication context)
        {
            _Context = context;
            Repository = new RealizationRepository(_Context);
            ManSneakersViewData = Repository.ReadDataSneakersMan();
        }
        public IActionResult CatalogManProductView()
        {
            var ManSneakersView = ManSneakersViewData;
            return View("/Views/ManProduct/ManProductView.cshtml", ManSneakersView);
        }
        [HttpPost]
        public IActionResult SortingProduct(string color, int price, int size)
        {
            var SortedProduct = ManSneakersViewData;
            if (color != null)
            {
                SortedProduct = ManSneakersViewData.Where(x => x.Color == color);
            }
            if (price != 0)
            {
                SortedProduct = ManSneakersViewData.Where(x => x.Price <= price);
            }
            if (size != 0)
            {
                SortedProduct = ManSneakersViewData.Where(x => x.Size == size);
            }
            return View("/Views/ManProduct/ManProductView.cshtml", SortedProduct);
        }

        [HttpPost]
        public IActionResult AddCart(string name, int size, string country, string color, int price, string pictures)
        {
            DateTime time = DateTime.Now;
            Repository.AddCartProduct(name, size, country, color, price, time, pictures);
            return View("/Views/ManProduct/ManProductView.cshtml", ManSneakersViewData);
        }
    }

}

SeakerSop/Controllers/MyOrdersController.cs
using Microsoft.AspNetCore.Mvc;
using SeakerSop.Models;
using SeakerSop.Repository;

namespace SeakerSop.Controllers
{
    public class MyOrdersController : Controller
    {
        private readonly IRepository Repository;
        private readonly DbContextApplication _Context;
        public const string SessionKeyId = "IdUserKey";
        public MyOrdersController(DbContextApplication context)
        {
            _Context = context;
            Repository = new RealizationRepository(_Context);
        }
        [HttpGet]
        public IActionResult MyOrdersView()
        {
            int? idUser = HttpContext.Session.GetInt32(SessionKeyId);
            var MyOrdersView = Repository.MyOrders(idUser);
            return View("/Views/Ordering/MyOrderingStory.cshtml",MyOrdersView);
        }
           

    }
}

SeakerSop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SeakerSop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SeakerSop.styles.css" asp-append-version="true" />
</head>
<body>
    </style>
   <header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-black border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="nav-link text-white" asp-area="" asp-controller="MainPage" asp-action="Index">SneakerShop</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                        <a class="nav-link text-white" asp-area="" asp-controller="ManProduct" asp-action="CatalogManProductView">Man</a>
                    </li>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="MyOrders" asp-action="MyOrdersView">My orders</a>
                    </li>
                    <li class="nav-item ms-auto">
                        <a class="nav-link text-white" asp-area="" asp-controller="Cart" asp-action="CartView">My Cart</a>
                    </li>
                    <li class="nav-item me-0">
                        <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="LoginView">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="RegistrationView">Registration</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SeakerSop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>